root: true

extends:
  - typescript
  - prettier
  - plugin:optimize-regex/recommended
  - plugin:regexp/recommended
  - plugin:sonarjs/recommended

plugins:
  - optimize-regex
  - regexp
  - sonarjs
